[workspace]
members = [
  "core/cce-ast",
  "core/cce-stream",
  "core/circelang-hash",
  "core/circelang-hash-proc",

  "lowlevel/cce-llast",

  "inference/cce-infer",
  "inference/cce-infer-ast",
  "inference/circelang-db",

  "ccec"
]