[package]
name = "circelang-db"
version = "0.0.1"
edition = "2021"

[dependencies]
cce-ast = { version = "0.0.1", path = "../../core/cce-ast" }
circelang-hash = { version = "0.0.1", path = "../../core/circelang-hash" }
