[package]
name = "cce-infer-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ast = { path = "../../core/cce-ast" }
cce-lowlevel = { path = "../../core/cce-lowlevel" }
cce-stream = { path = "../../core/cce-stream" }