[package]
name = "cce-infer-ast"
version = "0.0.1"
edition = "2021"

[dependencies]
cce-ast = { path = "../../core/cce-ast", version = "0.0.1" }
cce-llast = { path = "../../lowlevel/cce-llast", version = "0.0.1" }
cce-stream = { path = "../../core/cce-stream", version = "0.0.1" }