[package]
name = "cce-lowlevel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cce-stream = { path = "../cce-stream" }
thiserror = "1.0.40"
