[package]
name = "ccec"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
cce-ast = { path = "../core/cce-ast" }
cce-infer = { path = "../inference/cce-infer" }
cce-infer-ast = { path = "../inference/cce-infer-ast" }