[package]
name = "cce-lowlevel"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.13", features = ["full"], default-features = false }
thiserror = "1.0.40"
